version: "3.8"

volumes:
  dbdata:
networks:
  rotomnet:
services:
  db:
    image: mysql:8.0.28
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: pokemon_schema
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - rotomnet
    ports:
      - 3307:3306

  lb-app:
    build: ./haproxyAppConfig
    ports: 
      - "8443:8443"
      - "8084:8084"
    
    depends_on:
      - app1
      - app2
    networks:
      - rotomnet
    

  app1:
    image: manu/rotom-net
    restart: always
    depends_on:
      - db
      - lb-api
    networks:
      - rotomnet
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      # SPRING_JPA_HIBERNATE_DDL-AUTO: create #Must be comented after first launch!
      ROTOMNET_API_HOST: lb-api

  app2:
    image: manu/rotom-net
    restart: always
    depends_on:
      - db
      - lb-api
    networks:
      - rotomnet
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      ROTOMNET_API_HOST: lb-api


  lb-api:
    image: haproxy:2.1
    ports: 
      - "8085:8084"
    volumes:
      - "./haproxy-api.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"
    depends_on:
      - api1
      - api2
    networks:
      - rotomnet  

  api1:
    image: mrzabbah/api-rotom-net:latest
    restart: always
    networks:
      - rotomnet
      
  api2:
    image: mrzabbah/api-rotom-net:latest
    restart: always
    networks:
      - rotomnet
