version: "3.8"


services:
  db:
    image: mysql:8.0.28
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: pokemon_schema
    volumes:
      - dbdata:/var/lib/mysql

  app:
    image: mrzabbah/rotom-net:latest
    restart: always
    depends_on:
      - db
      - api
    ports:
      - 8443:8443
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      SPRING_JPA_HIBERNATE_DDL-AUTO: create #Must be comented after first launch!
      ROTOMNET_API_HOST: api

  api:
    image: mrzabbah/api-rotom-net:latest
    restart: always


volumes:
  dbdata:
      

