version: "3.8"

volumes:
  dbdata:
  dbslavedata:
networks:
  rotomnet:
services:
  db:
    image: mysql:5.7
    restart: always
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
        
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: pokemon_schema
    volumes:
      - ./master_config/my.cnf:/etc/mysql/my.cnf
      - ./master_config/data:/var/lib/mysql
      - ./master_config/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - rotomnet
      
  dbslave:
    image: mysql:5.7
    restart: always
    container_name: dbslave
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: pokemon_schema
    volumes:
      - ./slave_config/my.cnf:/etc/mysql/my.cnf
      - ./slave_config/data:/var/lib/mysql
      - ./slave_config/init.sql:/docker-entrypoint-initdb.d/init.sql
    depends_on:
      - db
    networks:
      - rotomnet
      
  proxysql:
    image: proxysql/proxysql:2.0.12
    restart: always
    container_name: proxysql
    volumes:
      - ./proxysql/proxysql.cnf:/etc/proxysql.cnf
      - ./proxysql/data:/var/lib/proxysql
    depends_on:
      - db
      - dbslave
    networks:
      - rotomnet


  lb-app:
    image: haproxy:2.1
    ports: 
      - "8443:8443"
      - "8084:8084"
    volumes:
      - "./haproxy-app.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"
    depends_on:
      - app1
      - app2
    networks:
      - rotomnet
    

  app1:
    image: mrzabbah/rotom-net:latest
    restart: always
    depends_on:
      - proxysql
      - lb-api
    networks:
      - rotomnet
    environment:
      MYSQL_HOST: db #No es mysql ya, ahora apunta al proxysql
      MYSQL_PORT: 3306 #No es el puerto de mysql, es el puerto de proxysql
      SPRING_JPA_HIBERNATE_DDL-AUTO: create #Must be comented after first launch!
      ROTOMNET_API_HOST: lb-api

  app2:
    image: mrzabbah/rotom-net:latest
    restart: always
    depends_on:
      - proxysql
      - lb-api
    networks:
      - rotomnet
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      ROTOMNET_API_HOST: lb-api


  lb-api:
    image: haproxy:2.1
    ports: 
      - "8085:8084"
    volumes:
      - "./haproxy-api.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"
    depends_on:
      - api1
      - api2
    networks:
      - rotomnet  

  api1:
    image: mrzabbah/api-rotom-net:latest
    restart: always
    networks:
      - rotomnet
      
  api2:
    image: mrzabbah/api-rotom-net:latest
    restart: always
    networks:
      - rotomnet
